name: Build website

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: checkout
        uses: actions/checkout@v3

      # Setup nodejs
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # Install Dependencies
      - name: Install dependencies
        run: npm install

      # Build project
      - name: Build project
        run: npm run build
